# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNS
pod 'Firebase'
pod 'Firebase/Database'
pod 'SVProgressHUD'
pod 'Firebase/Messaging'
pod 'SDWebImage'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'

end
