version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [redis-server]
    volumes:
      - ./data/redis:/data

  mysql:
    image: mysql/mysql-server:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      # Rollbarのトークン
      ROLLBAR_ACCESS_TOKEN:
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - learning_rails_bundle:/app/vendor/bundle
      - learning_rails_node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  learning_rails_bundle:
    driver: local
  learning_rails_node_modules:
    driver: local