# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '27.Ad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 27.Ad
  pod 'Google-Mobile-Ads-SDK'
	pod 'SwiftyStoreKit'

end
