version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - modules:/app/node_modules
    command: >
      bash -c "npm install --save next
      && npm install --save react
      && npm install --save react-dom
      && npm install --save redux
      && npm install --save react-redux
      && npm install --save redux-thunk
      && apt-get update
      && apt-get install -y vim
      && yarn install
      && bash"

volumes:
  modules:
    driver: local