# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '24.News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 24.News
  //アニメーション
  pod 'lottie-ios'
  //セグメントコントローラー
  pod 'SegementSlide'
  //通知
  pod 'ImpressiveNotifications'

end